services:

  redis:
    image: redis:7-alpine
    container_name: taskflow-redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:4-management
    hostname: taskflow-rabbitmq
    ports:
      - "127.0.0.1:5672:5672"
      - "127.0.0.1:15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: taskflow
      RABBITMQ_DEFAULT_PASS: taskflow_local
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: unless-stopped

  postgres:
    image: postgres:17-alpine
    ports:
      - "127.0.0.1:5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_local
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  rabbitmq_data:
  postgres_data:
